### ISSUE TITLE
Where is draft about signed updates?

### ISSUE THREAD

**Issue by SJLC** [sbabic/swupdate#10]
Saw signed updates on the TODO list of roadmap page, and it mentioned an existing draft for that feature. Where is it?

**Comment by sbabic** [comment]
On 24/11/2015 04:17, S. Lockwood-Childs wrote:
> Saw signed updates on the TODO list of roadmap page, and it mentioned an
> existing draft for that feature. Where is it?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbabic/swupdate/issues/10>.

I starting writing some documentation about how to implement it, but I
had to suspend it and delay it later. Sure signed images is a feature I
want to have in the project, but there is not yet any implementation.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by SJLC** [comment]
I'm interested in at least seeing the notes... might end up doing a branch with a prototype that you could at least take a look at for ideas when it is time to add that feature, even if it's not the final implementation.

**Comment by sbabic** [comment]
On Tuesday, November 24, 2015 at 1:34:13 AM UTC-8, Stefano Babic wrote:
> On 24/11/2015 04:17, S. Lockwood-Childs wrote:
> > Saw signed updates on the TODO list of roadmap page, and it mentioned an
> > existing draft for that feature. Where is it?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sbabic/swupdate/issues/10>.
> 
> I starting writing some documentation about how to implement it, but I
> had to suspend it and delay it later. Sure signed images is a feature I
> want to have in the project, but there is not yet any implementation.
> 
> Best regards,
> Stefano Babic

Are you interested in discussing signed update approach yet? I will be needing another signed updater pretty soon, and I'd like to work towards something that could eventually be upstreamed rather than just making a local fork.
