### ISSUE TITLE
Segmentation fault with Swupdate v2016.07.0

### ISSUE THREAD

**Issue by joerg-krause** [sbabic/swupdate#15]
```
# swupdate -b "0 1 2 3 4 5" -d SERVER -r 3
Swupdate v2016.07.0

Licensed under GPLv2. See source distribution for detailed copyright notices.

Registered handlers:
	flash
	raw
	rawfile
	ubivol
	ubipartition
	shellscript
	preinstall
	postinstall
	uboot
Main loop Daemon
[NOTIFY] : SWUPDATE started :  Software Update started !
[NOTIFY] : SWUPDATE downloading :  
scan_for_ubi_devices
Version 4.2.1
[NOTIFY] : SWUPDATE running :  Installing image rootfs.ubifs into volume /dev/ubi2_1(rootfs)
Segmentation fault
```

Probably related to https://github.com/sbabic/swupdate/commit/79d312e558098313c35161be0fad49eb4fc3001b? If so, mind to release a fixed version v2016.07.1 as v2016.10 is in two months?

Btw. can you also provide a tagged version for v2016.10-rc1? Many thanks!

**Comment by joerg-krause** [comment]
For sure not related to https://github.com/sbabic/swupdate/commit/79d312e558098313c35161be0fad49eb4fc3001b, but properly to https://github.com/sbabic/swupdate/commit/e739e798252569f07ee87e5b78e7d905dcc38196 as v2016.10-rc1 is working fine.

**Comment by sbabic** [comment]
Hi Jörg,

On 05/08/2016 14:35, Jörg Krause wrote:
> For sure not related to 79d312e
> <https://github.com/sbabic/swupdate/commit/79d312e558098313c35161be0fad49eb4fc3001b>,
> but properly to e739e79

Yes, it is. The segfault happened by calling the fw_setenv() function.
79d312e fixes it.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================
