### ISSUE TITLE
Cannot build SWUpdate: include/flash.h:26:24: fatal error: mtd/libmtd.h: No such file or directory

### ISSUE THREAD

**Issue by anadahz** [sbabic/swupdate#16]
Which is the recommended way of building SWUpdate?

`$ make`
```
  CC      core/swupdate.o
In file included from core/swupdate.c:47:0:
include/flash.h:26:24: fatal error: mtd/libmtd.h: No such file or directory
 #include <mtd/libmtd.h>
                        ^
compilation terminated.
scripts/Makefile.build:168: recipe for target 'core/swupdate.o' failed
make[1]: *** [core/swupdate.o] Error 1
Makefile:419: recipe for target 'core' failed
make: *** [core] Error 2
```
`# dpkg -l *mtd*`
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  libmtdev-dev                                  1.1.5-1                     amd64                       Multitouch Protocol Translation Library - dev files
ii  libmtdev1:amd64                               1.1.5-1                     amd64                       Multitouch Protocol Translation Library - shared library
un  mtd-tools                                     <none>                      <none>                      (no description available)
ii  mtd-utils                                     1:1.5.2-1                   amd64                       Memory Technology Device Utilities
ii  mtdev-tools                                   1.1.5-1                     amd64                       Multitouch Protocol Translation Library - test tools
```

**Comment by alsam** [comment]
The same build error for Linux Arch:
```sh
uname -a
Linux 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
```
```sh
ls -l /usr/include/mtd
total 44
-rw-r--r-- 1 root root  1581 Aug  2 08:47 inftl-user.h
-rw-r--r-- 1 root root  9653 Aug  2 08:47 mtd-abi.h
-rw-r--r-- 1 root root  1178 Aug  2 08:47 mtd-user.h
-rw-r--r-- 1 root root  2052 Aug  2 08:47 nftl-user.h
-rw-r--r-- 1 root root 17610 Aug  2 08:47 ubi-user.h
```
```sh
find / -name libmtd.h 2> /dev/nul
```
not found.
In my understanding the header `/usr/include/mtd/libmtd.h` should have been installed with `packman -S mtd-utils`, shouldn't?

**Comment by sbabic** [comment]
Hi Alexander,

On 06/09/2016 14:36, Alexander Samoilov wrote:
> The same build error for Linux Arch:
> 

Please do not use github to send your question, but use the ML for that.

> uname -a
> Linux 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
> 
> ls -l /usr/include/mtd
> total 44
> -rw-r--r-- 1 root root  1581 Aug  2 08:47 inftl-user.h
> -rw-r--r-- 1 root root  9653 Aug  2 08:47 mtd-abi.h
> -rw-r--r-- 1 root root  1178 Aug  2 08:47 mtd-user.h
> -rw-r--r-- 1 root root  2052 Aug  2 08:47 nftl-user.h
> -rw-r--r-- 1 root root 17610 Aug  2 08:47 ubi-user.h
> 
> find / -name libmtd.h 2> /dev/nul
> 
> not found.
> In my understanding the header |/usr/include/mtd/libmtd.h| should have
> been installed with |packman -S mtd-utils|, shouldn't?

SWUpdate is thought to work on an embedded system - changes are done in
the buildsystems (Yocto and builroot are supported) to make it
buildable. That includes slight changes how mtd-utils are built to
expose headers and libraries (libmtd.a and libubi.a).

If you want to build it on the host, I presume, you have to make
yourself these changes. Do not expect the desktop distros have support
for SWUpdate.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by alsam** [comment]
Hi Stefano, thanks for the answer.
