### ISSUE TITLE
Undefined variable when compiling core/swupdate with undefined CONFIG_DOWNLOAD

### ISSUE THREAD

**Issue by stephan-kempkes** [sbabic/swupdate#19]
Since commit 7ffe16a, in core/swupdate.c the variable opt_d is only defined when CONFIG_DOWNLOAD is defined (line 466). However, this variable isn't guarded in line 776. Thus, the file currently does not compile when CONFIG_DOWNLOAD is not defined.

**Comment by sbabic** [comment]
A patch was already sent to ML - I merged it today.
Please use the ML (swupdate@googlegroups.com for questions/issues/patches - it is the official way to get help for this project.
