### ISSUE TITLE
File limitations

### ISSUE THREAD

**Issue by berlinembedded** [sbabic/swupdate#21]
Is there any limitation about the maximum allowed file length per file in the cpio archive? I tried to pack 2 GiB images with cpio, but swupdate failed to extract these.
If I understand the cpio manual correctly, the limit should be 4GiB for the cpio-CRC format. Are there any limitations in swupdate you know about? 

From the cpio manual:
`
--format=format

    [copy-in,copy-out,copy-pass]
    Use archive format format. The valid formats are listed below with file size limits for individual files in parentheses; the same names are also recognized in all-caps. The default in copy-in mode is to automatically detect the archive format, and in copy-out mode is ‘bin’.

    ‘bin’

        The obsolete binary format. (2147483647 bytes)
    ‘odc’

        The old (POSIX.1) portable format. (8589934591 bytes)
    ‘newc’

        The new (SVR4) portable format, which supports file systems having more than 65536 i-nodes. (4294967295 bytes)
    ‘crc’

        The new (SVR4) portable format with a checksum added.
    ‘tar’

        The old tar format. (8589934591 bytes)
    ‘ustar’

        The POSIX.1 tar format. Also recognizes GNU tar archives, which are similar but not identical. (8589934591 bytes)
    ‘hpbin’

        The obsolete binary format used by HPUX’s cpio (which stores device files differently).
    ‘hpodc’

        The portable format used by HPUX’s cpio (which stores device files differently). 
`

**Comment by sbabic** [comment]
Hi,

On 05/12/2016 14:38, berlinembedded wrote:
> Is there any limitation about the maximum allowed file length per file
> in the cpio archive? I tried to pack 2 GiB images with cpio, but
> swupdate failed to extract these.

I can remember that I had some big images in the past, but I do not
tested recently. Have you checked deeply what is happening ?

> If I understand the cpio manual correctly, the limit should be 4GiB for
> the cpio-CRC format. Are there any limitations in swupdate you know about?
> 
> From the cpio manual:
> `
> --format=format

SWUpdate des not call via "system" any additional tool. That means that
the cpio is parsed directly by own code. Length is a 32bit value, and
more as 4GB for a single image is not allowed. But less, yes.

What do you get running the update with the -v flag ?

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by flar-developer** [comment]
Hello.

As i see in cpiohdr.h, filehdr::size is of type long. May be the maximum file is a signed number?
Then the maximum file size would be 2GiB-1 bytes.

Best regards,
Anton.
