### ISSUE TITLE
Allow specifing volume name instead of mtd device in flash handler

### ISSUE THREAD

**Issue by martijndegouw** [sbabic/swupdate#23]
Hi,

I would like to specifiy the mtd name instead if the device in the sw-description file.
On our board we try to keep the names the same, but the order, size or even availability might be different.

I'm thinking about adding a get_mtd_from_volume() to the flash handler.
What is your opinion about this?

Regards, Martijn de Gouw

**Comment by sbabic** [comment]
Hi Martiin,

please use the ML to send questions regarding this project instead of
github - thanks !


On 10/12/2016 12:11, Martijn de Gouw wrote:
> Hi,
> 
> I would like to specifiy the mtd name instead if the device in the
> sw-description file.
> On our board we try to keep the names the same, but the order, size or
> even availability might be different.
> 

ok

> I'm thinking about adding a get_mtd_from_volume() to the flash handler.
> What is your opinion about this?

The mtd_info() structure already contains the name. Anyway, I do not
understand the relationship with the volume. If you use UBI volumes, you
do not need the MTD names. And we have already the flexibility you want
to reach. Maybe you can better explain your use case: are you using this
on not UBI devices, maybe NOR ?

The main point is to have everything consistent. All flash handlers
(flash, ubi) must be adapted and the same for the MTD_BLACKLIST, that
allows now just a list of mtd device numbers.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by sbabic** [comment]
Hi Stefano,

On Saturday, December 10, 2016 at 12:59:40 PM UTC+1, Stefano Babic wrote:
> Hi Martiin,
> 
> please use the ML to send questions regarding this project instead of
> github - thanks !

I'll just reply here, hope it helps.

> 
> On 10/12/2016 12:11, Martijn de Gouw wrote:
> > Hi,
> > 
> > I would like to specifiy the mtd name instead if the device in the
> > sw-description file.
> > On our board we try to keep the names the same, but the order, size or
> > even availability might be different.
> > 
> 
> ok
> 
> > I'm thinking about adding a get_mtd_from_volume() to the flash handler.
> > What is your opinion about this?
> 
> The mtd_info() structure already contains the name. Anyway, I do not
> understand the relationship with the volume. If you use UBI volumes, you
> do not need the MTD names. And we have already the flexibility you want
> to reach. Maybe you can better explain your use case: are you using this
> on not UBI devices, maybe NOR ?

Yes, we are using NOR flash. For example:
# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00100000 00020000 "reserved"
mtd1: 00100000 00020000 "dtb"
mtd2: 00400000 00020000 "kernel"

I would like to specify "kernel", not mtd2.

> 
> The main point is to have everything consistent. All flash handlers
> (flash, ubi) must be adapted and the same for the MTD_BLACKLIST, that
> allows now just a list of mtd device numbers.
> 
> Best regards,
> Stefano Babic
> 
> -- 
> =====================================================================
> DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
> HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
> Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
> =====================================================================

Regards, Martijn

**Comment by sbabic** [comment]
Hi Martijn,

On 10/12/2016 13:38, mdegouw@gmail.com wrote:
> Hi Stefano,
> 
> On Saturday, December 10, 2016 at 12:59:40 PM UTC+1, Stefano Babic wrote:
>> Hi Martiin,
>>
>> please use the ML to send questions regarding this project instead of
>> github - thanks !
> 
> I'll just reply here, hope it helps.

Yes, it works

> 
> Yes, we are using NOR flash. For example:
> # cat /proc/mtd
> dev:    size   erasesize  name
> mtd0: 00100000 00020000 "reserved"
> mtd1: 00100000 00020000 "dtb"
> mtd2: 00400000 00020000 "kernel"
> 
> I would like to specify "kernel", not mtd2.

ok - the internal flash structure in SWUpdate has already all
information. You need to bind it now with sw-description.

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by sbabic** [comment]
Hi Stefano,

Op zondag 11 december 2016 21:34:25 UTC+1 schreef Stefano Babic:
> Hi Martijn,
> 
> On 10/12/2016 13:38, mdegouw@gmail.com wrote:
> > Hi Stefano,
> > 
> > Yes, we are using NOR flash. For example:
> > # cat /proc/mtd
> > dev:    size   erasesize  name
> > mtd0: 00100000 00020000 "reserved"
> > mtd1: 00100000 00020000 "dtb"
> > mtd2: 00400000 00020000 "kernel"
> > 
> > I would like to specify "kernel", not mtd2.
> 
> ok - the internal flash structure in SWUpdate has already all
> information. You need to bind it now with sw-description.

Ok, I found the "mtdname" property, which is put in "path" by the external parser.
Are you okay with reusing this approach for the json/cfg parser?
I can add get_mtd_from_name() to the flash_handler then.

Are you okay with this approach?

Regards, Martijn

**Comment by sbabic** [comment]
Hi Martjin,

On 12/12/2016 10:13, karenschellekens@gmail.com wrote:
> Hi Stefano,
> 
> Op zondag 11 december 2016 21:34:25 UTC+1 schreef Stefano Babic:
>> Hi Martijn,
>>
>> On 10/12/2016 13:38, mdegouw@gmail.com wrote:
>>> Hi Stefano,
>>>
>>> Yes, we are using NOR flash. For example:
>>> # cat /proc/mtd
>>> dev:    size   erasesize  name
>>> mtd0: 00100000 00020000 "reserved"
>>> mtd1: 00100000 00020000 "dtb"
>>> mtd2: 00400000 00020000 "kernel"
>>>
>>> I would like to specify "kernel", not mtd2.
>>
>> ok - the internal flash structure in SWUpdate has already all
>> information. You need to bind it now with sw-description.
> 
> Ok, I found the "mtdname" property, which is put in "path" by the external parser.
> Are you okay with reusing this approach for the json/cfg parser?

ok, you can use it. I guess this is undocumented, so please change
documentation, too.

> I can add get_mtd_from_name() to the flash_handler then.
> 
> Are you okay with this approach?
> 

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================
